from copy import deepcopy

SKILLS = {
    "SAP": {
        "label": "SAP Configuration",
        "target": 4.6,
        "future_target": 4.8,
        "weight": 0.23,
        "criticality": "Critical",
        "required_experts": 3,
        "daily_downtime_cost": 2500.0,
        "default_recovery_days": 30,
        "related_keywords": ["sap"],
    },
    "FoodSafety": {
        "label": "Food Safety Certification",
        "target": 4.5,
        "future_target": 4.7,
        "weight": 0.22,
        "criticality": "Critical",
        "required_experts": 2,
        "daily_downtime_cost": 3000.0,
        "default_recovery_days": 14,
        "related_keywords": ["food safety", "food"],
    },
    "Robotics": {
        "label": "Industrial Robotics",
        "target": 4.6,
        "future_target": 4.9,
        "weight": 0.20,
        "criticality": "High",
        "required_experts": 2,
        "daily_downtime_cost": 2800.0,
        "default_recovery_days": 21,
        "related_keywords": ["robotics", "industrial"],
    },
    "ColdChain": {
        "label": "Cold Chain Operations",
        "target": 4.3,
        "future_target": 4.6,
        "weight": 0.18,
        "criticality": "High",
        "required_experts": 3,
        "daily_downtime_cost": 2200.0,
        "default_recovery_days": 14,
        "related_keywords": ["cold chain", "cold"],
    },
    "AIOps": {
        "label": "AI-Assisted Operations",
        "target": 4.3,
        "future_target": 4.8,
        "weight": 0.17,
        "criticality": "High",
        "required_experts": 2,
        "daily_downtime_cost": 2000.0,
        "default_recovery_days": 30,
        "related_keywords": ["aiops", "ai-assisted", "automation", "analytics", "predictive", "machine learning"],
    },
}

EMPLOYEES = [
    {
        "id": "alex",
        "name": "Alex Morgan",
        "role": "Operations Systems Lead",
        "department": "Operations",
        "team": "Enterprise Systems",
        "confidence": 0.96,
        "freshness_days": 18,
        "growth_rate": 0.04,  # skill points / month
        "interests": ["automation", "systems resilience", "SAP"],
        "skills": {"SAP": 5.0, "FoodSafety": 3.1, "Robotics": 4.6, "ColdChain": 4.0, "AIOps": 4.2},
        "projects": ["ERP Modernization", "Line Automation"],
        "certifications": ["SAP Advanced"],
    },
    {
        "id": "maria",
        "name": "Maria Santos",
        "role": "Process Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.91,
        "freshness_days": 21,
        "growth_rate": 0.18,
        "interests": ["automation leadership", "SAP", "robotics"],
        "skills": {"SAP": 4.1, "FoodSafety": 4.4, "Robotics": 3.2, "ColdChain": 4.0, "AIOps": 3.3},
        "projects": ["SAP Rollout", "Packaging Upgrade"],
        "certifications": ["Lean Manufacturing"],
    },
    {
        "id": "john",
        "name": "John Lee",
        "role": "Quality Specialist",
        "department": "Quality",
        "team": "Food Safety",
        "confidence": 0.94,
        "freshness_days": 10,
        "growth_rate": 0.08,
        "interests": ["food safety leadership", "quality systems"],
        "skills": {"SAP": 2.5, "FoodSafety": 4.8, "Robotics": 2.1, "ColdChain": 3.2, "AIOps": 2.0},
        "projects": ["Audit Readiness", "Supplier Quality"],
        "certifications": ["Food Safety Level 2"],
    },
    {
        "id": "priya",
        "name": "Priya Shah",
        "role": "Supply Chain Analyst",
        "department": "Supply Chain",
        "team": "Cold Chain",
        "confidence": 0.87,
        "freshness_days": 34,
        "growth_rate": 0.21,
        "interests": ["automation analytics", "machine vision", "cold chain"],
        "skills": {"SAP": 3.4, "FoodSafety": 3.3, "Robotics": 4.0, "ColdChain": 4.7, "AIOps": 3.8},
        "projects": ["Cold Chain Optimization", "Vision Pilot"],
        "certifications": ["Data Analytics"],
    },
    {
        "id": "sam",
        "name": "Sam Rivera",
        "role": "Maintenance Engineer",
        "department": "Operations",
        "team": "Plant Reliability",
        "confidence": 0.88,
        "freshness_days": 55,
        "growth_rate": 0.12,
        "interests": ["predictive maintenance", "robotics"],
        "skills": {"SAP": 3.2, "FoodSafety": 3.6, "Robotics": 4.3, "ColdChain": 3.5, "AIOps": 3.4},
        "projects": ["Predictive Maintenance Pilot"],
        "certifications": ["Industrial Maintenance"],
    },
    {
        "id": "lena",
        "name": "Lena Park",
        "role": "R&D Specialist",
        "department": "R&D",
        "team": "Product Innovation",
        "confidence": 0.90,
        "freshness_days": 92,
        "growth_rate": 0.05,
        "interests": ["product innovation", "Korean market R&D"],
        "skills": {"SAP": 2.2, "FoodSafety": 4.2, "Robotics": 2.8, "ColdChain": 3.0, "AIOps": 3.1},
        "projects": ["Korean Product Launch"],
        "certifications": ["Food Science"],
    },
    {
        "id": "daniel",
        "name": "Daniel Brooks",
        "role": "Operations Systems Lead",
        "department": "Operations",
        "team": "Enterprise Systems",
        "confidence": 0.90,
        "freshness_days": 26,
        "growth_rate": 0.06,
        "interests": ["systems reliability", "SAP governance", "incident response"],
        "skills": {"SAP": 3.8, "FoodSafety": 2.9, "Robotics": 3.5, "ColdChain": 3.8, "AIOps": 4.0},
        "projects": ["Incident Response Playbook", "SAP Governance Review"],
        "certifications": ["SAP Core"],
    },
    {
        "id": "kevin",
        "name": "Kevin Nguyen",
        "role": "Process Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.89,
        "freshness_days": 29,
        "growth_rate": 0.16,
        "interests": ["SAP rollout", "process validation", "cross-training"],
        "skills": {"SAP": 3.9, "FoodSafety": 4.2, "Robotics": 3.8, "ColdChain": 3.9, "AIOps": 3.4},
        "projects": ["SAP Rollout", "Line Validation"],
        "certifications": ["Six Sigma Green Belt"],
    },
    {
        "id": "hannah",
        "name": "Hannah Kim",
        "role": "Quality Specialist",
        "department": "Quality",
        "team": "Food Safety",
        "confidence": 0.91,
        "freshness_days": 17,
        "growth_rate": 0.07,
        "interests": ["food safety audits", "supplier quality"],
        "skills": {"SAP": 2.8, "FoodSafety": 4.0, "Robotics": 2.4, "ColdChain": 3.6, "AIOps": 2.2},
        "projects": ["Supplier Audit Program"],
        "certifications": ["Food Safety Level 1"],
    },
    {
        "id": "olivia",
        "name": "Olivia Grant",
        "role": "Supply Chain Analyst",
        "department": "Supply Chain",
        "team": "Cold Chain",
        "confidence": 0.90,
        "freshness_days": 22,
        "growth_rate": 0.14,
        "interests": ["cold chain logistics", "demand planning"],
        "skills": {"SAP": 3.6, "FoodSafety": 3.4, "Robotics": 3.0, "ColdChain": 4.1, "AIOps": 3.5},
        "projects": ["Cold Chain Optimization", "Demand Planning Pilot"],
        "certifications": ["Supply Chain Analytics"],
    },
    {
        "id": "ethan",
        "name": "Ethan Cole",
        "role": "Maintenance Engineer",
        "department": "Operations",
        "team": "Plant Reliability",
        "confidence": 0.89,
        "freshness_days": 31,
        "growth_rate": 0.08,
        "interests": ["reliability engineering", "robotics maintenance"],
        "skills": {"SAP": 2.9, "FoodSafety": 3.3, "Robotics": 4.0, "ColdChain": 3.4, "AIOps": 3.0},
        "projects": ["Predictive Maintenance Pilot"],
        "certifications": ["Reliability-Centered Maintenance"],
    },
    {
        "id": "maya",
        "name": "Maya Johnson",
        "role": "R&D Specialist",
        "department": "R&D",
        "team": "Product Innovation",
        "confidence": 0.88,
        "freshness_days": 38,
        "growth_rate": 0.13,
        "interests": ["product innovation", "sensory science"],
        "skills": {"SAP": 2.4, "FoodSafety": 4.0, "Robotics": 3.0, "ColdChain": 3.2, "AIOps": 3.5},
        "projects": ["Flavor Innovation Pilot"],
        "certifications": ["Food Science"],
    },
    {
        "id": "noah",
        "name": "Noah Williams",
        "role": "Robotics Engineer",
        "department": "Engineering",
        "team": "Automation",
        "confidence": 0.93,
        "freshness_days": 14,
        "growth_rate": 0.17,
        "interests": ["industrial robotics", "automation strategy"],
        "skills": {"SAP": 3.5, "FoodSafety": 2.9, "Robotics": 4.7, "ColdChain": 3.2, "AIOps": 4.0},
        "projects": ["Line Automation", "Robotics Standards"],
        "certifications": ["Robotics Systems Integration"],
    },
    {
        "id": "sofia",
        "name": "Sofia Martinez",
        "role": "Robotics Engineer",
        "department": "Engineering",
        "team": "Automation",
        "confidence": 0.90,
        "freshness_days": 20,
        "growth_rate": 0.15,
        "interests": ["machine vision", "automation strategy"],
        "skills": {"SAP": 3.3, "FoodSafety": 3.1, "Robotics": 4.1, "ColdChain": 3.5, "AIOps": 4.1},
        "projects": ["Vision Pilot", "Line Automation"],
        "certifications": ["Machine Vision Fundamentals"],
    },
    {
        "id": "liam",
        "name": "Liam Carter",
        "role": "Mechanical Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.90,
        "freshness_days": 27,
        "growth_rate": 0.06,
        "interests": ["mechanical design", "equipment reliability"],
        "skills": {"SAP": 3.1, "FoodSafety": 3.0, "Robotics": 4.2, "ColdChain": 3.8, "AIOps": 3.2},
        "projects": ["Line Automation", "Equipment Redesign"],
        "certifications": ["Mechanical Engineering Design"],
    },
    {
        "id": "grace",
        "name": "Grace Wilson",
        "role": "Mechanical Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.88,
        "freshness_days": 33,
        "growth_rate": 0.12,
        "interests": ["equipment design", "continuous improvement"],
        "skills": {"SAP": 3.0, "FoodSafety": 3.2, "Robotics": 3.9, "ColdChain": 3.7, "AIOps": 3.3},
        "projects": ["Equipment Redesign", "Continuous Improvement Program"],
        "certifications": ["Lean Six Sigma"],
    },
]

# Simple in-memory store for hackathon speed. Replace with Supabase/Postgres later.
STATE = {
    "employees": deepcopy(EMPLOYEES),
    "future_requirements": {k: v["future_target"] for k, v in SKILLS.items()},
    "business_impact": {
        k: {
            "daily_downtime_cost": v["daily_downtime_cost"],
            "default_recovery_days": v["default_recovery_days"],
        }
        for k, v in SKILLS.items()
    },
}


def reset_state():
    STATE["employees"] = deepcopy(EMPLOYEES)
    STATE["future_requirements"] = {k: v["future_target"] for k, v in SKILLS.items()}
    STATE["business_impact"] = {
        k: {
            "daily_downtime_cost": v["daily_downtime_cost"],
            "default_recovery_days": v["default_recovery_days"],
        }
        for k, v in SKILLS.items()
    }
