from copy import deepcopy

SKILLS = {
    "SAP": {
        "label": "SAP Configuration",
        "target": 4.6,
        "future_target": 4.8,
        "weight": 0.23,
        "criticality": "Critical",
        "required_experts": 3,
        "daily_downtime_cost": 2500.0,
        "default_recovery_days": 30,
        "related_keywords": ["sap"],
    },
    "FoodSafety": {
        "label": "Food Safety Certification",
        "target": 4.5,
        "future_target": 4.7,
        "weight": 0.22,
        "criticality": "Critical",
        "required_experts": 2,
        "daily_downtime_cost": 3000.0,
        "default_recovery_days": 14,
        "related_keywords": ["food safety", "food"],
    },
    "Robotics": {
        "label": "Industrial Robotics",
        "target": 4.6,
        "future_target": 4.9,
        "weight": 0.20,
        "criticality": "High",
        "required_experts": 2,
        "daily_downtime_cost": 2800.0,
        "default_recovery_days": 21,
        "related_keywords": ["robotics", "industrial"],
    },
    "ColdChain": {
        "label": "Cold Chain Operations",
        "target": 4.3,
        "future_target": 4.6,
        "weight": 0.18,
        "criticality": "High",
        "required_experts": 3,
        "daily_downtime_cost": 2200.0,
        "default_recovery_days": 14,
        "related_keywords": ["cold chain", "cold"],
    },
    "AIOps": {
        "label": "AI-Assisted Operations",
        "target": 4.3,
        "future_target": 4.8,
        "weight": 0.17,
        "criticality": "High",
        "required_experts": 2,
        "daily_downtime_cost": 2000.0,
        "default_recovery_days": 30,
        "related_keywords": ["aiops", "ai-assisted", "automation", "analytics", "predictive", "machine learning"],
    },
}

# gaps / backup / plan / why / future_match / future_gap are narrative fields
# mirrored from the frontend's demoEmployees[] (app/static/index.html) so the
# two datasets describe the same 16 people consistently. No engine.py function
# reads them today - they exist for parity with the frontend and for any
# future endpoint that wants to return an employee's full profile.
EMPLOYEES = [
    {
        "id": "alex",
        "name": "Derek Falkner",
        "role": "Operations Systems Lead",
        "department": "Operations",
        "team": "Enterprise Systems",
        "confidence": 0.96,
        "freshness_days": 18,
        "growth_rate": 0.04,  # skill points / month
        "interests": ["automation", "systems resilience", "SAP"],
        "skills": {"SAP": 5.0, "FoodSafety": 3.1, "Robotics": 4.6, "ColdChain": 4.0, "AIOps": 4.2},
        "projects": ["ERP Modernization", "Line Automation"],
        "certifications": ["SAP Advanced"],
        "gaps": ["Food Safety Certification backup depth"],
        "future_match": 92,
        "backup": "Critical expert; strongest SAP owner and automation specialist.",
        "plan": "Knowledge transfer to Camila; documentation; two paired live SAP cycles.",
        "why": "Highest SAP evidence, strong automation work history, and verified manager confidence.",
        "future_gap": "Needs broader food-safety certification coverage to remain resilient across plant operations.",
    },
    {
        "id": "maria",
        "name": "Camila Reyes",
        "role": "Process Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.91,
        "freshness_days": 21,
        "growth_rate": 0.18,
        "interests": ["automation leadership", "SAP", "robotics"],
        "skills": {"SAP": 4.1, "FoodSafety": 4.4, "Robotics": 3.2, "ColdChain": 4.0, "AIOps": 3.3},
        "projects": ["SAP Rollout", "Packaging Upgrade"],
        "certifications": ["Lean Manufacturing"],
        "gaps": ["Advanced robotics", "SAP architecture depth"],
        "future_match": 91,
        "backup": "Best internal SAP succession candidate; Ready <6 Months.",
        "plan": "SAP cross-training, Derek mentorship, one production configuration project.",
        "why": "Strong adjacent SAP evidence, recent rollout work, high growth, and explicit SAP career interest.",
        "future_gap": "Robotics 3.2 -> 4.2 and SAP architecture depth are the main 2027 readiness gaps.",
    },
    {
        "id": "john",
        "name": "Desmond Whitaker",
        "role": "Quality Specialist",
        "department": "Quality",
        "team": "Food Safety",
        "confidence": 0.94,
        "freshness_days": 10,
        "growth_rate": 0.08,
        "interests": ["food safety leadership", "quality systems"],
        "skills": {"SAP": 2.5, "FoodSafety": 4.8, "Robotics": 2.1, "ColdChain": 3.2, "AIOps": 2.0},
        "projects": ["Audit Readiness", "Supplier Quality"],
        "certifications": ["Food Safety Level 2"],
        "gaps": ["Food Safety Level 3 certification", "automation exposure"],
        "future_match": 86,
        "backup": "Best Food Safety backup candidate; Ready Now after certification renewal.",
        "plan": "Complete Level 3 certification, shadow current lead, own next audit-prep checklist.",
        "why": "Highest food-safety proficiency, freshest evidence, and explicit quality leadership interest.",
        "future_gap": "Food Safety Level 3 verification plus basic automation exposure are required for 2027 quality leadership.",
    },
    {
        "id": "priya",
        "name": "Ishani Rao",
        "role": "Supply Chain Analyst",
        "department": "Supply Chain",
        "team": "Cold Chain",
        "confidence": 0.87,
        "freshness_days": 34,
        "growth_rate": 0.21,
        "interests": ["automation analytics", "machine vision", "cold chain"],
        "skills": {"SAP": 3.4, "FoodSafety": 3.3, "Robotics": 4.0, "ColdChain": 4.7, "AIOps": 3.8},
        "projects": ["Cold Chain Optimization", "Vision Pilot"],
        "certifications": ["Data Analytics"],
        "gaps": ["Food Safety certification", "SAP configuration"],
        "future_match": 88,
        "backup": "Strong robotics / cold-chain stretch candidate; Ready <6 Months.",
        "plan": "Robotics project rotation, machine-vision mentoring, verification on live work.",
        "why": "Non-obvious fit: strong robotics adjacency, best cold-chain score, rapid growth, and relevant career interest.",
        "future_gap": "Needs SAP configuration exposure and one verified robotics delivery to qualify for the 2027 automation program.",
    },
    {
        "id": "sam",
        "name": "Travis Ondrasek",
        "role": "Maintenance Engineer",
        "department": "Operations",
        "team": "Plant Reliability",
        "confidence": 0.88,
        "freshness_days": 55,
        "growth_rate": 0.12,
        "interests": ["predictive maintenance", "robotics"],
        "skills": {"SAP": 3.2, "FoodSafety": 3.6, "Robotics": 4.3, "ColdChain": 3.5, "AIOps": 3.4},
        "projects": ["Predictive Maintenance Pilot"],
        "certifications": ["Industrial Maintenance"],
        "gaps": ["AI operations", "SAP"],
        "future_match": 84,
        "backup": "Robotics backup candidate; Ready 6-12 Months.",
        "plan": "AI Ops training, robotics project leadership, SAP basics.",
        "why": "Strong robotics and maintenance evidence with relevant interests, but SAP/AIOps gaps remain.",
        "future_gap": "AI Ops 3.4 -> 4.0 and SAP 3.2 -> 3.8 for future predictive-maintenance leadership.",
    },
    {
        "id": "lena",
        "name": "Yuna Cho",
        "role": "R&D Specialist",
        "department": "R&D",
        "team": "Product Innovation",
        "confidence": 0.90,
        "freshness_days": 92,
        "growth_rate": 0.05,
        "interests": ["product innovation", "Korean market R&D"],
        "skills": {"SAP": 2.2, "FoodSafety": 4.2, "Robotics": 2.8, "ColdChain": 3.0, "AIOps": 3.1},
        "projects": ["Korean Product Launch"],
        "certifications": ["Food Science"],
        "gaps": ["evidence freshness", "backup documentation"],
        "future_match": 80,
        "backup": "Specialized R&D knowledge risk; Ready 6-12 Months backups required.",
        "plan": "Capture product-development knowledge, pair junior R&D backup, refresh evidence.",
        "why": "Unique Korean-market R&D experience is business-critical but evidence is aging and concentrated.",
        "future_gap": "Needs refreshed evidence and a verified junior backup before the next R&D cycle.",
    },
    {
        "id": "daniel",
        "name": "Marcus Feldman",
        "role": "Operations Systems Lead",
        "department": "Operations",
        "team": "Enterprise Systems",
        "confidence": 0.90,
        "freshness_days": 26,
        "growth_rate": 0.06,
        "interests": ["systems reliability", "SAP governance", "incident response"],
        "skills": {"SAP": 3.8, "FoodSafety": 2.9, "Robotics": 3.5, "ColdChain": 3.8, "AIOps": 4.0},
        "projects": ["Incident Response Playbook", "SAP Governance Review"],
        "certifications": ["SAP Core"],
        "gaps": ["Food Safety exposure", "SAP architecture depth"],
        "future_match": 84,
        "backup": "Secondary SAP/AI Ops backup for Derek Falkner; Ready Now.",
        "plan": "Shadow Derek on SAP architecture decisions, complete Food Safety fundamentals.",
        "why": "Second-strongest SAP and AI Ops profile in Operations, immediately available.",
        "future_gap": "Needs Food Safety fundamentals and deeper SAP architecture ownership for 2027 continuity.",
    },
    {
        "id": "kevin",
        "name": "Trevor Nakamura",
        "role": "Process Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.89,
        "freshness_days": 29,
        "growth_rate": 0.16,
        "interests": ["SAP rollout", "process validation", "cross-training"],
        "skills": {"SAP": 3.9, "FoodSafety": 4.2, "Robotics": 3.8, "ColdChain": 3.9, "AIOps": 3.4},
        "projects": ["SAP Rollout", "Line Validation"],
        "certifications": ["Six Sigma Green Belt"],
        "gaps": ["AI Ops exposure"],
        "future_match": 90,
        "backup": "Best available SAP/Food Safety succession candidate alongside Camila; Ready Now.",
        "plan": "AI Ops fundamentals, shadow the SAP configuration change process.",
        "why": "Broad, balanced skill profile with strong SAP and Food Safety evidence, actively growing.",
        "future_gap": "AI Ops 3.4 -> 4.0 is the main 2027 gap; otherwise well-positioned.",
    },
    {
        "id": "hannah",
        "name": "Josephine Okafor",
        "role": "Quality Specialist",
        "department": "Quality",
        "team": "Food Safety",
        "confidence": 0.91,
        "freshness_days": 17,
        "growth_rate": 0.07,
        "interests": ["food safety audits", "supplier quality"],
        "skills": {"SAP": 2.8, "FoodSafety": 4.0, "Robotics": 2.4, "ColdChain": 3.6, "AIOps": 2.2},
        "projects": ["Supplier Audit Program"],
        "certifications": ["Food Safety Level 1"],
        "gaps": ["Food Safety Level 3", "automation exposure"],
        "future_match": 82,
        "backup": "Second Food Safety backup after Desmond Whitaker; Ready Now for routine audits.",
        "plan": "Level 3 certification, cross-train on automation basics.",
        "why": "Freshest Food Safety evidence after Desmond, active supplier-audit work.",
        "future_gap": "Level 3 certification and automation basics needed for 2027 audit leadership.",
    },
    {
        "id": "olivia",
        "name": "Simone Beaulieu",
        "role": "Supply Chain Analyst",
        "department": "Supply Chain",
        "team": "Cold Chain",
        "confidence": 0.90,
        "freshness_days": 22,
        "growth_rate": 0.14,
        "interests": ["cold chain logistics", "demand planning"],
        "skills": {"SAP": 3.6, "FoodSafety": 3.4, "Robotics": 3.0, "ColdChain": 4.1, "AIOps": 3.5},
        "projects": ["Cold Chain Optimization", "Demand Planning Pilot"],
        "certifications": ["Supply Chain Analytics"],
        "gaps": ["Robotics exposure"],
        "future_match": 87,
        "backup": "Strong Cold Chain backup alongside Ishani; Ready Now.",
        "plan": "Robotics fundamentals, pair with Ishani on the vision-pilot rollout.",
        "why": "Second-highest Cold Chain score, consistent growth, relevant analytics background.",
        "future_gap": "Robotics 3.0 -> 4.0 for 2027 automated cold-chain monitoring.",
    },
    {
        "id": "ethan",
        "name": "Cormac Doyle",
        "role": "Maintenance Engineer",
        "department": "Operations",
        "team": "Plant Reliability",
        "confidence": 0.89,
        "freshness_days": 31,
        "growth_rate": 0.08,
        "interests": ["reliability engineering", "robotics maintenance"],
        "skills": {"SAP": 2.9, "FoodSafety": 3.3, "Robotics": 4.0, "ColdChain": 3.4, "AIOps": 3.0},
        "projects": ["Predictive Maintenance Pilot"],
        "certifications": ["Reliability-Centered Maintenance"],
        "gaps": ["SAP", "AI Ops"],
        "future_match": 80,
        "backup": "Robotics backup alongside Travis Ondrasek; Ready <6 Months.",
        "plan": "SAP basics, AI Ops fundamentals, shadow predictive-maintenance dashboards.",
        "why": "Strong robotics maintenance evidence, works the same predictive-maintenance program as Travis.",
        "future_gap": "SAP 2.9 -> 3.8 and AI Ops 3.0 -> 4.0 for future predictive-maintenance leadership.",
    },
    {
        "id": "maya",
        "name": "Talia Bloom",
        "role": "R&D Specialist",
        "department": "R&D",
        "team": "Product Innovation",
        "confidence": 0.88,
        "freshness_days": 38,
        "growth_rate": 0.13,
        "interests": ["product innovation", "sensory science"],
        "skills": {"SAP": 2.4, "FoodSafety": 4.0, "Robotics": 3.0, "ColdChain": 3.2, "AIOps": 3.5},
        "projects": ["Flavor Innovation Pilot"],
        "certifications": ["Food Science"],
        "gaps": ["evidence freshness", "SAP"],
        "future_match": 79,
        "backup": "Second R&D knowledge holder alongside Yuna Cho; Ready <6 Months.",
        "plan": "Pair with Yuna on active projects, refresh SAP basics.",
        "why": "Second-strongest R&D profile, actively growing, real succession depth for R&D risk.",
        "future_gap": "Needs paired documentation work with Yuna before the next R&D cycle.",
    },
    {
        "id": "noah",
        "name": "Jonah Whitcomb",
        "role": "Robotics Engineer",
        "department": "Engineering",
        "team": "Automation",
        "confidence": 0.93,
        "freshness_days": 14,
        "growth_rate": 0.17,
        "interests": ["industrial robotics", "automation strategy"],
        "skills": {"SAP": 3.5, "FoodSafety": 2.9, "Robotics": 4.7, "ColdChain": 3.2, "AIOps": 4.0},
        "projects": ["Line Automation", "Robotics Standards"],
        "certifications": ["Robotics Systems Integration"],
        "gaps": ["Food Safety exposure"],
        "future_match": 93,
        "backup": "Strongest available Robotics backup; Ready Now.",
        "plan": "Food Safety fundamentals, formalize robotics standards documentation.",
        "why": "Highest Robotics score in the company with strong, fresh evidence and AI Ops overlap.",
        "future_gap": "Minimal - Food Safety exposure is the only material 2027 gap.",
    },
    {
        "id": "sofia",
        "name": "Valentina Cruz",
        "role": "Robotics Engineer",
        "department": "Engineering",
        "team": "Automation",
        "confidence": 0.90,
        "freshness_days": 20,
        "growth_rate": 0.15,
        "interests": ["machine vision", "automation strategy"],
        "skills": {"SAP": 3.3, "FoodSafety": 3.1, "Robotics": 4.1, "ColdChain": 3.5, "AIOps": 4.1},
        "projects": ["Vision Pilot", "Line Automation"],
        "certifications": ["Machine Vision Fundamentals"],
        "gaps": ["SAP depth"],
        "future_match": 89,
        "backup": "Second Robotics/AI Ops backup alongside Jonah; Ready Now.",
        "plan": "SAP fundamentals, extend the machine-vision pilot to the Cold Chain line.",
        "why": "Strong, balanced Robotics and AI Ops profile with active vision-pilot work.",
        "future_gap": "SAP 3.3 -> 4.2 to round out automation-program readiness.",
    },
    {
        "id": "liam",
        "name": "Connor MacAllister",
        "role": "Mechanical Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.90,
        "freshness_days": 27,
        "growth_rate": 0.06,
        "interests": ["mechanical design", "equipment reliability"],
        "skills": {"SAP": 3.1, "FoodSafety": 3.0, "Robotics": 4.2, "ColdChain": 3.8, "AIOps": 3.2},
        "projects": ["Line Automation", "Equipment Redesign"],
        "certifications": ["Mechanical Engineering Design"],
        "gaps": ["Food Safety", "AI Ops"],
        "future_match": 83,
        "backup": "Mechanical/Robotics backup for automation projects; Ready Now.",
        "plan": "Food Safety basics, AI Ops fundamentals.",
        "why": "Strong mechanical and robotics evidence directly relevant to the automation program.",
        "future_gap": "Food Safety and AI Ops are the main gaps for broader 2027 automation ownership.",
    },
    {
        "id": "grace",
        "name": "Adelaide Kowalski",
        "role": "Mechanical Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.88,
        "freshness_days": 33,
        "growth_rate": 0.12,
        "interests": ["equipment design", "continuous improvement"],
        "skills": {"SAP": 3.0, "FoodSafety": 3.2, "Robotics": 3.9, "ColdChain": 3.7, "AIOps": 3.3},
        "projects": ["Equipment Redesign", "Continuous Improvement Program"],
        "certifications": ["Lean Six Sigma"],
        "gaps": ["SAP", "AI Ops"],
        "future_match": 81,
        "backup": "Second Mechanical Engineering backup alongside Connor; Ready <6 Months.",
        "plan": "SAP and AI Ops fundamentals, pair with Connor on redesign projects.",
        "why": "Solid, growing mechanical profile with continuous-improvement focus.",
        "future_gap": "SAP 3.0 -> 3.8 and AI Ops 3.3 -> 4.0 for 2027 mechanical-automation readiness.",
    },
]

# Former employees never contribute to readiness/coverage/qualified-count/
# succession calculations - they are historical knowledge only, mirroring
# the frontend's formerEmployees[]. Deliberately NOT part of EMPLOYEES or
# STATE["employees"], and no engine.py function accepts this list.
FORMER_EMPLOYEES = [
    {
        "id": "raj",
        "name": "Arun Mehta",
        "former_role": "Senior Process Engineer",
        "department": "Engineering",
        "left_year": 2025,
        "tenure_years": 6,
        "skills": {"SAP": 4.4, "FoodSafety": 4.1, "Robotics": 4.0},
        "description": "Former Process Engineering role-holder. Historical work can support cross-training for process and SAP coverage.",
        "artifacts": ["Packaging Line SOP", "SAP changeover guide", "Robotics commissioning notes"],
    },
    {
        "id": "nina",
        "name": "Bridget Callahan",
        "former_role": "Process Engineer",
        "department": "Engineering",
        "left_year": 2024,
        "tenure_years": 4,
        "skills": {"FoodSafety": 4.2, "SAP": 3.9, "Robotics": 3.7},
        "description": "Former Process Engineer. Archived process-validation work can accelerate cross-training.",
        "artifacts": ["Yield-loss checklist", "Process validation template", "Packaging troubleshooting guide"],
    },
    {
        "id": "victor",
        "name": "Dmitri Volkov",
        "former_role": "Robotics Engineer",
        "department": "Engineering",
        "left_year": 2025,
        "tenure_years": 5,
        "skills": {"Robotics": 4.8, "AIOps": 3.9, "SAP": 3.2},
        "description": "Former Robotics Engineer. Commissioning and PLC documentation can accelerate robotics cross-training.",
        "artifacts": ["Robot commissioning checklist", "PLC backup archive", "Safety validation notes"],
    },
    {
        "id": "chloe",
        "name": "Freya Lindqvist",
        "former_role": "Robotics Engineer",
        "department": "Engineering",
        "left_year": 2024,
        "tenure_years": 4,
        "skills": {"Robotics": 4.4, "AIOps": 4.0, "ColdChain": 3.3},
        "description": "Former Robotics Engineer with reusable machine-vision and cobot knowledge.",
        "artifacts": ["Vision tuning guide", "Cobot risk assessment", "Robot maintenance handoff"],
    },
    {
        "id": "robert",
        "name": "Gordon Ashworth",
        "former_role": "Mechanical Engineer",
        "department": "Engineering",
        "left_year": 2025,
        "tenure_years": 8,
        "skills": {"Robotics": 4.0, "ColdChain": 3.8, "SAP": 3.0},
        "description": "Former Mechanical Engineer. Equipment drawings and failure history can support mechanical coverage.",
        "artifacts": ["Critical equipment drawings", "Mechanical failure library", "Engineering change notes"],
    },
    {
        "id": "elena",
        "name": "Rosalind Kessler",
        "former_role": "Maintenance Engineer",
        "department": "Operations",
        "left_year": 2024,
        "tenure_years": 6,
        "skills": {"Robotics": 4.1, "ColdChain": 3.5, "FoodSafety": 3.2},
        "description": "Former Maintenance Engineer. Reliability documentation can support cross-training and outage coverage.",
        "artifacts": ["PM standard work", "Failure-mode library", "Maintenance handoff checklist"],
    },
]

# Simple in-memory store for hackathon speed. Replace with Supabase/Postgres later.
STATE = {
    "employees": deepcopy(EMPLOYEES),
    "future_requirements": {k: v["future_target"] for k, v in SKILLS.items()},
    "business_impact": {
        k: {
            "daily_downtime_cost": v["daily_downtime_cost"],
            "default_recovery_days": v["default_recovery_days"],
        }
        for k, v in SKILLS.items()
    },
}


def reset_state():
    STATE["employees"] = deepcopy(EMPLOYEES)
    STATE["future_requirements"] = {k: v["future_target"] for k, v in SKILLS.items()}
    STATE["business_impact"] = {
        k: {
            "daily_downtime_cost": v["daily_downtime_cost"],
            "default_recovery_days": v["default_recovery_days"],
        }
        for k, v in SKILLS.items()
    }
