from copy import deepcopy

SKILLS = {
    "SAP": {
        "label": "SAP Configuration",
        "target": 4.6,
        "future_target": 4.8,
        "weight": 0.23,
        "criticality": "Critical",
        "required_experts": 3,
        "daily_downtime_cost": 2500.0,
        "default_recovery_days": 30,
        "related_keywords": ["sap"],
    },
    "FoodSafety": {
        "label": "Food Safety Certification",
        "target": 4.5,
        "future_target": 4.7,
        "weight": 0.22,
        "criticality": "Critical",
        "required_experts": 2,
        "daily_downtime_cost": 3000.0,
        "default_recovery_days": 14,
        "related_keywords": ["food safety", "food"],
    },
    "Robotics": {
        "label": "Industrial Robotics",
        "target": 4.6,
        "future_target": 4.9,
        "weight": 0.20,
        "criticality": "High",
        "required_experts": 2,
        "daily_downtime_cost": 2800.0,
        "default_recovery_days": 21,
        "related_keywords": ["robotics", "industrial"],
    },
    "ColdChain": {
        "label": "Cold Chain Operations",
        "target": 4.3,
        "future_target": 4.6,
        "weight": 0.18,
        "criticality": "High",
        "required_experts": 3,
        "daily_downtime_cost": 2200.0,
        "default_recovery_days": 14,
        "related_keywords": ["cold chain", "cold"],
    },
    "AIOps": {
        "label": "AI-Assisted Operations",
        "target": 4.3,
        "future_target": 4.8,
        "weight": 0.17,
        "criticality": "High",
        "required_experts": 2,
        "daily_downtime_cost": 2000.0,
        "default_recovery_days": 30,
        "related_keywords": ["aiops", "ai-assisted", "automation", "analytics", "predictive", "machine learning"],
    },
}

# gaps / backup / plan / why / future_match / future_gap are narrative fields
# mirrored from the frontend's demoEmployees[] (app/static/index.html) so the
# two datasets describe the same 16 people consistently. No engine.py function
# reads them today - they exist for parity with the frontend and for any
# future endpoint that wants to return an employee's full profile.
EMPLOYEES = [
    {
        "id": "alex",
        "name": "Derek Falkner",
        "role": "Operations Systems Lead",
        "department": "Operations",
        "team": "Enterprise Systems",
        "confidence": 0.96,
        "freshness_days": 18,
        "growth_rate": 0.04,  # skill points / month
        "interests": ["automation", "systems resilience", "SAP"],
        "skills": {"SAP": 5.0, "FoodSafety": 3.1, "Robotics": 4.6, "ColdChain": 4.0, "AIOps": 4.2},
        "projects": ["ERP Modernization", "Line Automation"],
        "certifications": ["SAP Advanced"],
        "gaps": ["Food Safety Certification backup depth"],
        "future_match": 92,
        "backup": "Critical expert; strongest SAP owner and automation specialist.",
        "plan": "Knowledge transfer to Camila; documentation; two paired live SAP cycles.",
        "why": "Highest SAP evidence, strong automation work history, and verified manager confidence.",
        "future_gap": "Needs broader food-safety certification coverage to remain resilient across plant operations.",
    },
    {
        "id": "maria",
        "name": "Camila Reyes",
        "role": "Process Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.91,
        "freshness_days": 21,
        "growth_rate": 0.18,
        "interests": ["automation leadership", "SAP", "robotics"],
        "skills": {"SAP": 4.1, "FoodSafety": 4.4, "Robotics": 3.2, "ColdChain": 4.0, "AIOps": 3.3},
        "projects": ["SAP Rollout", "Packaging Upgrade"],
        "certifications": ["Lean Manufacturing"],
        "gaps": ["Advanced robotics", "SAP architecture depth"],
        "future_match": 91,
        "backup": "Best internal SAP succession candidate; Ready <6 Months.",
        "plan": "SAP cross-training, Derek mentorship, one production configuration project.",
        "why": "Strong adjacent SAP evidence, recent rollout work, high growth, and explicit SAP career interest.",
        "future_gap": "Robotics 3.2 -> 4.2 and SAP architecture depth are the main 2027 readiness gaps.",
    },
    {
        "id": "john",
        "name": "Desmond Whitaker",
        "role": "Quality Specialist",
        "department": "Quality",
        "team": "Food Safety",
        "confidence": 0.94,
        "freshness_days": 10,
        "growth_rate": 0.08,
        "interests": ["food safety leadership", "quality systems"],
        "skills": {"SAP": 2.5, "FoodSafety": 4.8, "Robotics": 2.1, "ColdChain": 3.2, "AIOps": 2.0},
        "projects": ["Audit Readiness", "Supplier Quality"],
        "certifications": ["Food Safety Level 2"],
        "gaps": ["Food Safety Level 3 certification", "automation exposure"],
        "future_match": 86,
        "backup": "Best Food Safety backup candidate; Ready Now after certification renewal.",
        "plan": "Complete Level 3 certification, shadow current lead, own next audit-prep checklist.",
        "why": "Highest food-safety proficiency, freshest evidence, and explicit quality leadership interest.",
        "future_gap": "Food Safety Level 3 verification plus basic automation exposure are required for 2027 quality leadership.",
    },
    {
        "id": "priya",
        "name": "Ishani Rao",
        "role": "Supply Chain Analyst",
        "department": "Supply Chain",
        "team": "Cold Chain",
        "confidence": 0.87,
        "freshness_days": 34,
        "growth_rate": 0.21,
        "interests": ["automation analytics", "machine vision", "cold chain"],
        "skills": {"SAP": 3.4, "FoodSafety": 3.3, "Robotics": 4.0, "ColdChain": 4.7, "AIOps": 3.8},
        "projects": ["Cold Chain Optimization", "Vision Pilot"],
        "certifications": ["Data Analytics"],
        "gaps": ["Food Safety certification", "SAP configuration"],
        "future_match": 88,
        "backup": "Strong robotics / cold-chain stretch candidate; Ready <6 Months.",
        "plan": "Robotics project rotation, machine-vision mentoring, verification on live work.",
        "why": "Non-obvious fit: strong robotics adjacency, best cold-chain score, rapid growth, and relevant career interest.",
        "future_gap": "Needs SAP configuration exposure and one verified robotics delivery to qualify for the 2027 automation program.",
    },
    {
        "id": "sam",
        "name": "Travis Ondrasek",
        "role": "Maintenance Engineer",
        "department": "Operations",
        "team": "Plant Reliability",
        "confidence": 0.88,
        "freshness_days": 55,
        "growth_rate": 0.12,
        "interests": ["predictive maintenance", "robotics"],
        "skills": {"SAP": 3.2, "FoodSafety": 3.6, "Robotics": 4.3, "ColdChain": 3.5, "AIOps": 3.4},
        "projects": ["Predictive Maintenance Pilot"],
        "certifications": ["Industrial Maintenance"],
        "gaps": ["AI operations", "SAP"],
        "future_match": 84,
        "backup": "Robotics backup candidate; Ready 6-12 Months.",
        "plan": "AI Ops training, robotics project leadership, SAP basics.",
        "why": "Strong robotics and maintenance evidence with relevant interests, but SAP/AIOps gaps remain.",
        "future_gap": "AI Ops 3.4 -> 4.0 and SAP 3.2 -> 3.8 for future predictive-maintenance leadership.",
    },
    {
        "id": "lena",
        "name": "Yuna Cho",
        "role": "R&D Specialist",
        "department": "R&D",
        "team": "Product Innovation",
        "confidence": 0.90,
        "freshness_days": 92,
        "growth_rate": 0.05,
        "interests": ["product innovation", "Korean market R&D"],
        "skills": {"SAP": 2.2, "FoodSafety": 4.2, "Robotics": 2.8, "ColdChain": 3.0, "AIOps": 3.1},
        "projects": ["Korean Product Launch"],
        "certifications": ["Food Science"],
        "gaps": ["evidence freshness", "backup documentation"],
        "future_match": 80,
        "backup": "Specialized R&D knowledge risk; Ready 6-12 Months backups required.",
        "plan": "Capture product-development knowledge, pair junior R&D backup, refresh evidence.",
        "why": "Unique Korean-market R&D experience is business-critical but evidence is aging and concentrated.",
        "future_gap": "Needs refreshed evidence and a verified junior backup before the next R&D cycle.",
    },
    {
        "id": "daniel",
        "name": "Marcus Feldman",
        "role": "Operations Systems Lead",
        "department": "Operations",
        "team": "Enterprise Systems",
        "confidence": 0.90,
        "freshness_days": 26,
        "growth_rate": 0.06,
        "interests": ["systems reliability", "SAP governance", "incident response"],
        "skills": {"SAP": 3.8, "FoodSafety": 2.9, "Robotics": 3.5, "ColdChain": 3.8, "AIOps": 4.0},
        "projects": ["Incident Response Playbook", "SAP Governance Review"],
        "certifications": ["SAP Core"],
        "gaps": ["Food Safety exposure", "SAP architecture depth"],
        "future_match": 84,
        "backup": "Secondary SAP/AI Ops backup for Derek Falkner; Ready Now.",
        "plan": "Shadow Derek on SAP architecture decisions, complete Food Safety fundamentals.",
        "why": "Second-strongest SAP and AI Ops profile in Operations, immediately available.",
        "future_gap": "Needs Food Safety fundamentals and deeper SAP architecture ownership for 2027 continuity.",
    },
    {
        "id": "kevin",
        "name": "Trevor Nakamura",
        "role": "Process Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.89,
        "freshness_days": 29,
        "growth_rate": 0.16,
        "interests": ["SAP rollout", "process validation", "cross-training"],
        "skills": {"SAP": 3.9, "FoodSafety": 4.2, "Robotics": 3.8, "ColdChain": 3.9, "AIOps": 3.4},
        "projects": ["SAP Rollout", "Line Validation"],
        "certifications": ["Six Sigma Green Belt"],
        "gaps": ["AI Ops exposure"],
        "future_match": 90,
        "backup": "Best available SAP/Food Safety succession candidate alongside Camila; Ready Now.",
        "plan": "AI Ops fundamentals, shadow the SAP configuration change process.",
        "why": "Broad, balanced skill profile with strong SAP and Food Safety evidence, actively growing.",
        "future_gap": "AI Ops 3.4 -> 4.0 is the main 2027 gap; otherwise well-positioned.",
    },
    {
        "id": "hannah",
        "name": "Josephine Okafor",
        "role": "Quality Specialist",
        "department": "Quality",
        "team": "Food Safety",
        "confidence": 0.91,
        "freshness_days": 17,
        "growth_rate": 0.07,
        "interests": ["food safety audits", "supplier quality"],
        "skills": {"SAP": 2.8, "FoodSafety": 4.0, "Robotics": 2.4, "ColdChain": 3.6, "AIOps": 2.2},
        "projects": ["Supplier Audit Program"],
        "certifications": ["Food Safety Level 1"],
        "gaps": ["Food Safety Level 3", "automation exposure"],
        "future_match": 82,
        "backup": "Second Food Safety backup after Desmond Whitaker; Ready Now for routine audits.",
        "plan": "Level 3 certification, cross-train on automation basics.",
        "why": "Freshest Food Safety evidence after Desmond, active supplier-audit work.",
        "future_gap": "Level 3 certification and automation basics needed for 2027 audit leadership.",
    },
    {
        "id": "olivia",
        "name": "Simone Beaulieu",
        "role": "Supply Chain Analyst",
        "department": "Supply Chain",
        "team": "Cold Chain",
        "confidence": 0.90,
        "freshness_days": 22,
        "growth_rate": 0.14,
        "interests": ["cold chain logistics", "demand planning"],
        "skills": {"SAP": 3.6, "FoodSafety": 3.4, "Robotics": 3.0, "ColdChain": 4.1, "AIOps": 3.5},
        "projects": ["Cold Chain Optimization", "Demand Planning Pilot"],
        "certifications": ["Supply Chain Analytics"],
        "gaps": ["Robotics exposure"],
        "future_match": 87,
        "backup": "Strong Cold Chain backup alongside Ishani; Ready Now.",
        "plan": "Robotics fundamentals, pair with Ishani on the vision-pilot rollout.",
        "why": "Second-highest Cold Chain score, consistent growth, relevant analytics background.",
        "future_gap": "Robotics 3.0 -> 4.0 for 2027 automated cold-chain monitoring.",
    },
    {
        "id": "ethan",
        "name": "Cormac Doyle",
        "role": "Maintenance Engineer",
        "department": "Operations",
        "team": "Plant Reliability",
        "confidence": 0.89,
        "freshness_days": 31,
        "growth_rate": 0.08,
        "interests": ["reliability engineering", "robotics maintenance"],
        "skills": {"SAP": 2.9, "FoodSafety": 3.3, "Robotics": 4.0, "ColdChain": 3.4, "AIOps": 3.0},
        "projects": ["Predictive Maintenance Pilot"],
        "certifications": ["Reliability-Centered Maintenance"],
        "gaps": ["SAP", "AI Ops"],
        "future_match": 80,
        "backup": "Robotics backup alongside Travis Ondrasek; Ready <6 Months.",
        "plan": "SAP basics, AI Ops fundamentals, shadow predictive-maintenance dashboards.",
        "why": "Strong robotics maintenance evidence, works the same predictive-maintenance program as Travis.",
        "future_gap": "SAP 2.9 -> 3.8 and AI Ops 3.0 -> 4.0 for future predictive-maintenance leadership.",
    },
    {
        "id": "maya",
        "name": "Talia Bloom",
        "role": "R&D Specialist",
        "department": "R&D",
        "team": "Product Innovation",
        "confidence": 0.88,
        "freshness_days": 38,
        "growth_rate": 0.13,
        "interests": ["product innovation", "sensory science"],
        "skills": {"SAP": 2.4, "FoodSafety": 4.0, "Robotics": 3.0, "ColdChain": 3.2, "AIOps": 3.5},
        "projects": ["Flavor Innovation Pilot"],
        "certifications": ["Food Science"],
        "gaps": ["evidence freshness", "SAP"],
        "future_match": 79,
        "backup": "Second R&D knowledge holder alongside Yuna Cho; Ready <6 Months.",
        "plan": "Pair with Yuna on active projects, refresh SAP basics.",
        "why": "Second-strongest R&D profile, actively growing, real succession depth for R&D risk.",
        "future_gap": "Needs paired documentation work with Yuna before the next R&D cycle.",
    },
    {
        "id": "noah",
        "name": "Jonah Whitcomb",
        "role": "Robotics Engineer",
        "department": "Engineering",
        "team": "Automation",
        "confidence": 0.93,
        "freshness_days": 14,
        "growth_rate": 0.17,
        "interests": ["industrial robotics", "automation strategy"],
        "skills": {"SAP": 3.5, "FoodSafety": 2.9, "Robotics": 4.7, "ColdChain": 3.2, "AIOps": 4.0},
        "projects": ["Line Automation", "Robotics Standards"],
        "certifications": ["Robotics Systems Integration"],
        "gaps": ["Food Safety exposure"],
        "future_match": 93,
        "backup": "Strongest available Robotics backup; Ready Now.",
        "plan": "Food Safety fundamentals, formalize robotics standards documentation.",
        "why": "Highest Robotics score in the company with strong, fresh evidence and AI Ops overlap.",
        "future_gap": "Minimal - Food Safety exposure is the only material 2027 gap.",
    },
    {
        "id": "sofia",
        "name": "Valentina Cruz",
        "role": "Robotics Engineer",
        "department": "Engineering",
        "team": "Automation",
        "confidence": 0.90,
        "freshness_days": 20,
        "growth_rate": 0.15,
        "interests": ["machine vision", "automation strategy"],
        "skills": {"SAP": 3.3, "FoodSafety": 3.1, "Robotics": 4.1, "ColdChain": 3.5, "AIOps": 4.1},
        "projects": ["Vision Pilot", "Line Automation"],
        "certifications": ["Machine Vision Fundamentals"],
        "gaps": ["SAP depth"],
        "future_match": 89,
        "backup": "Second Robotics/AI Ops backup alongside Jonah; Ready Now.",
        "plan": "SAP fundamentals, extend the machine-vision pilot to the Cold Chain line.",
        "why": "Strong, balanced Robotics and AI Ops profile with active vision-pilot work.",
        "future_gap": "SAP 3.3 -> 4.2 to round out automation-program readiness.",
    },
    {
        "id": "liam",
        "name": "Connor MacAllister",
        "role": "Mechanical Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.90,
        "freshness_days": 27,
        "growth_rate": 0.06,
        "interests": ["mechanical design", "equipment reliability"],
        "skills": {"SAP": 3.1, "FoodSafety": 3.0, "Robotics": 4.2, "ColdChain": 3.8, "AIOps": 3.2},
        "projects": ["Line Automation", "Equipment Redesign"],
        "certifications": ["Mechanical Engineering Design"],
        "gaps": ["Food Safety", "AI Ops"],
        "future_match": 83,
        "backup": "Mechanical/Robotics backup for automation projects; Ready Now.",
        "plan": "Food Safety basics, AI Ops fundamentals.",
        "why": "Strong mechanical and robotics evidence directly relevant to the automation program.",
        "future_gap": "Food Safety and AI Ops are the main gaps for broader 2027 automation ownership.",
    },
    {
        "id": "grace",
        "name": "Adelaide Kowalski",
        "role": "Mechanical Engineer",
        "department": "Engineering",
        "team": "Plant Engineering",
        "confidence": 0.88,
        "freshness_days": 33,
        "growth_rate": 0.12,
        "interests": ["equipment design", "continuous improvement"],
        "skills": {"SAP": 3.0, "FoodSafety": 3.2, "Robotics": 3.9, "ColdChain": 3.7, "AIOps": 3.3},
        "projects": ["Equipment Redesign", "Continuous Improvement Program"],
        "certifications": ["Lean Six Sigma"],
        "gaps": ["SAP", "AI Ops"],
        "future_match": 81,
        "backup": "Second Mechanical Engineering backup alongside Connor; Ready <6 Months.",
        "plan": "SAP and AI Ops fundamentals, pair with Connor on redesign projects.",
        "why": "Solid, growing mechanical profile with continuous-improvement focus.",
        "future_gap": "SAP 3.0 -> 3.8 and AI Ops 3.3 -> 4.0 for 2027 mechanical-automation readiness.",
    },
]

# The 24 employees below mirror app/static/index.html's demoEmployees[]
# additions (5 people per role instead of 2) - kept in sync so
# /api/strategy/analyze's readiness()/critical_gaps() reflect the same
# 40-person workforce the frontend displays, not a stale 16-person
# subset. All deliberately stay below the 90%-of-target qualification
# bar on every skill, same as the frontend, so no existing coverage or
# single-point-risk number moves.
EMPLOYEES += [
    {
        "id": "e-onav", "name": "Priya Nair", "role": "Operations Systems Lead", "department": "Operations", "team": "Enterprise Systems",
        "confidence": 0.84, "freshness_days": 40, "growth_rate": 0.09,
        "interests": ["systems administration", "SAP basics"],
        "skills": {"SAP": 3.9, "FoodSafety": 2.6, "Robotics": 3.8, "ColdChain": 3.5, "AIOps": 3.6},
        "projects": ["ERP Modernization"], "certifications": ["SAP Fundamentals"],
        "gaps": ["SAP architecture depth", "Food Safety exposure"], "future_match": 68,
        "backup": "Developing - not yet a verified SAP backup.",
        "plan": "SAP architecture shadowing under Derek, Food Safety fundamentals.",
        "why": "Solid systems fundamentals; SAP depth is the main gap to close before backup-eligible.",
        "future_gap": "SAP 3.9 -> 4.8 is the main 2027 gap for this role.",
    },
    {
        "id": "e-oblk", "name": "Owen Blackwood", "role": "Operations Systems Lead", "department": "Operations", "team": "Enterprise Systems",
        "confidence": 0.81, "freshness_days": 55, "growth_rate": 0.07,
        "interests": ["plant operations", "process control"],
        "skills": {"SAP": 3.6, "FoodSafety": 2.8, "Robotics": 3.4, "ColdChain": 3.6, "AIOps": 3.3},
        "projects": ["Line Automation"], "certifications": [],
        "gaps": ["SAP configuration", "AI Ops"], "future_match": 63,
        "backup": "Developing - not yet a verified SAP backup.",
        "plan": "SAP configuration training, AI Ops fundamentals.",
        "why": "Broad operational exposure but evidence is thinner than the team's senior leads.",
        "future_gap": "SAP 3.6 -> 4.8 and AI Ops 3.3 -> 4.8 for 2027 readiness.",
    },
    {
        "id": "e-rsil", "name": "Renata Silva", "role": "Operations Systems Lead", "department": "Operations", "team": "Enterprise Systems",
        "confidence": 0.79, "freshness_days": 68, "growth_rate": 0.11,
        "interests": ["systems resilience"],
        "skills": {"SAP": 3.3, "FoodSafety": 2.5, "Robotics": 3.0, "ColdChain": 3.2, "AIOps": 3.0},
        "projects": ["Incident Response Playbook"], "certifications": [],
        "gaps": ["SAP configuration", "Robotics exposure"], "future_match": 58,
        "backup": "Developing - not yet a verified SAP backup.",
        "plan": "SAP configuration training, robotics fundamentals, refresh evidence.",
        "why": "Newest to the role; foundational skills present but need verified evidence.",
        "future_gap": "SAP 3.3 -> 4.8 is the largest 2027 gap for this role.",
    },
    {
        "id": "e-hibr", "name": "Hassan Ibrahim", "role": "Process Engineer", "department": "Engineering", "team": "Plant Engineering",
        "confidence": 0.86, "freshness_days": 25, "growth_rate": 0.14,
        "interests": ["process validation", "SAP rollout"],
        "skills": {"SAP": 3.7, "FoodSafety": 3.9, "Robotics": 3.4, "ColdChain": 3.6, "AIOps": 3.0},
        "projects": ["SAP Rollout"], "certifications": ["Process Validation"],
        "gaps": ["SAP architecture depth", "AI Ops"], "future_match": 70,
        "backup": "Developing SAP/Food Safety backup alongside Camila and Trevor.",
        "plan": "SAP architecture shadowing, AI Ops fundamentals.",
        "why": "Balanced profile close to backup-eligible on both SAP and Food Safety.",
        "future_gap": "AI Ops 3.0 -> 4.8 is the main 2027 gap.",
    },
    {
        "id": "e-lfer", "name": "Lucia Fernandez", "role": "Process Engineer", "department": "Engineering", "team": "Plant Engineering",
        "confidence": 0.83, "freshness_days": 33, "growth_rate": 0.16,
        "interests": ["packaging engineering", "cross-training"],
        "skills": {"SAP": 3.5, "FoodSafety": 3.7, "Robotics": 3.1, "ColdChain": 3.5, "AIOps": 2.9},
        "projects": ["Packaging Upgrade"], "certifications": [],
        "gaps": ["SAP configuration", "AI Ops"], "future_match": 66,
        "backup": "Developing - building toward SAP/Food Safety backup depth.",
        "plan": "SAP configuration training, AI Ops fundamentals.",
        "why": "Fast-growing profile; evidence still short of the backup-eligible bar.",
        "future_gap": "SAP 3.5 -> 4.8 and AI Ops 2.9 -> 4.8 for 2027 readiness.",
    },
    {
        "id": "e-pnov", "name": "Peter Novak", "role": "Process Engineer", "department": "Engineering", "team": "Plant Engineering",
        "confidence": 0.80, "freshness_days": 48, "growth_rate": 0.10,
        "interests": ["quality systems"],
        "skills": {"SAP": 3.2, "FoodSafety": 3.4, "Robotics": 2.9, "ColdChain": 3.3, "AIOps": 2.7},
        "projects": ["Line Validation"], "certifications": [],
        "gaps": ["SAP configuration", "Food Safety Level 3"], "future_match": 60,
        "backup": "Developing - not yet backup-eligible.",
        "plan": "SAP fundamentals, Food Safety certification track.",
        "why": "Steady generalist profile; no standout strength yet.",
        "future_gap": "SAP 3.2 -> 4.8 is the largest 2027 gap.",
    },
    {
        "id": "e-ameze", "name": "Amara Eze", "role": "Quality Specialist", "department": "Quality", "team": "Food Safety",
        "confidence": 0.87, "freshness_days": 22, "growth_rate": 0.09,
        "interests": ["food safety audits"],
        "skills": {"SAP": 2.3, "FoodSafety": 3.9, "Robotics": 1.9, "ColdChain": 3.0, "AIOps": 1.8},
        "projects": ["Supplier Audit Program"], "certifications": ["Food Safety Level 1"],
        "gaps": ["Food Safety Level 3", "automation exposure"], "future_match": 69,
        "backup": "Developing Food Safety backup alongside Desmond and Josephine.",
        "plan": "Level 3 certification track, automation basics.",
        "why": "Strong, fresh Food Safety evidence just below the verified-backup bar.",
        "future_gap": "Food Safety 3.9 -> 4.7 closes most of the 2027 gap.",
    },
    {
        "id": "e-fgran", "name": "Felix Grant", "role": "Quality Specialist", "department": "Quality", "team": "Food Safety",
        "confidence": 0.84, "freshness_days": 29, "growth_rate": 0.08,
        "interests": ["supplier quality"],
        "skills": {"SAP": 2.6, "FoodSafety": 3.7, "Robotics": 2.2, "ColdChain": 3.3, "AIOps": 2.0},
        "projects": ["Audit Readiness"], "certifications": [],
        "gaps": ["Food Safety Level 3", "automation exposure"], "future_match": 65,
        "backup": "Developing - building Food Safety depth.",
        "plan": "Level 3 certification, shadow senior audit leads.",
        "why": "Solid quality fundamentals; certification is the main gate to backup status.",
        "future_gap": "Food Safety 3.7 -> 4.7 for 2027 audit leadership.",
    },
    {
        "id": "e-npet", "name": "Nadia Petrov", "role": "Quality Specialist", "department": "Quality", "team": "Food Safety",
        "confidence": 0.81, "freshness_days": 44, "growth_rate": 0.06,
        "interests": ["quality systems"],
        "skills": {"SAP": 2.1, "FoodSafety": 3.5, "Robotics": 1.8, "ColdChain": 2.9, "AIOps": 1.7},
        "projects": [], "certifications": [],
        "gaps": ["Food Safety Level 2", "automation exposure"], "future_match": 59,
        "backup": "Developing - not yet backup-eligible.",
        "plan": "Food Safety Level 2 certification, project experience.",
        "why": "Newest to Quality; evidence needs verification and project exposure.",
        "future_gap": "Food Safety 3.5 -> 4.7 is the main 2027 gap.",
    },
    {
        "id": "e-mald", "name": "Marcus Aldrich", "role": "Supply Chain Analyst", "department": "Supply Chain", "team": "Cold Chain",
        "confidence": 0.85, "freshness_days": 27, "growth_rate": 0.17,
        "interests": ["cold chain logistics", "automation analytics"],
        "skills": {"SAP": 3.2, "FoodSafety": 3.1, "Robotics": 3.5, "ColdChain": 3.6, "AIOps": 3.4},
        "projects": ["Demand Planning Pilot"], "certifications": ["Data Analytics"],
        "gaps": ["Cold Chain depth", "SAP configuration"], "future_match": 71,
        "backup": "Developing Cold Chain backup alongside Ishani and Simone.",
        "plan": "Cold Chain verification on live work, SAP fundamentals.",
        "why": "Balanced, fast-growing profile close to backup-eligible on Cold Chain.",
        "future_gap": "Cold Chain 3.6 -> 4.6 is the main 2027 gap.",
    },
    {
        "id": "e-cobi", "name": "Chidi Obi", "role": "Supply Chain Analyst", "department": "Supply Chain", "team": "Cold Chain",
        "confidence": 0.82, "freshness_days": 39, "growth_rate": 0.13,
        "interests": ["demand planning"],
        "skills": {"SAP": 3.0, "FoodSafety": 2.9, "Robotics": 3.2, "ColdChain": 3.5, "AIOps": 3.1},
        "projects": ["Cold Chain Optimization"], "certifications": [],
        "gaps": ["Cold Chain depth", "Food Safety"], "future_match": 64,
        "backup": "Developing - building Cold Chain depth.",
        "plan": "Cold Chain verification, Food Safety basics.",
        "why": "Consistent generalist profile with real Cold Chain project exposure.",
        "future_gap": "Cold Chain 3.5 -> 4.6 for 2027 readiness.",
    },
    {
        "id": "e-ilars", "name": "Ingrid Larsen", "role": "Supply Chain Analyst", "department": "Supply Chain", "team": "Cold Chain",
        "confidence": 0.80, "freshness_days": 52, "growth_rate": 0.10,
        "interests": ["supply chain analytics"],
        "skills": {"SAP": 2.8, "FoodSafety": 2.7, "Robotics": 2.9, "ColdChain": 3.4, "AIOps": 2.8},
        "projects": [], "certifications": [],
        "gaps": ["Cold Chain depth", "SAP configuration"], "future_match": 58,
        "backup": "Developing - not yet backup-eligible.",
        "plan": "Cold Chain fundamentals, SAP basics, live project exposure.",
        "why": "Early-stage profile; no verified project evidence yet.",
        "future_gap": "Cold Chain 3.4 -> 4.6 is the largest 2027 gap.",
    },
    {
        "id": "e-tvit", "name": "Tomas Vitek", "role": "Maintenance Engineer", "department": "Operations", "team": "Plant Reliability",
        "confidence": 0.83, "freshness_days": 35, "growth_rate": 0.09,
        "interests": ["robotics maintenance"],
        "skills": {"SAP": 2.7, "FoodSafety": 3.0, "Robotics": 3.8, "ColdChain": 3.1, "AIOps": 2.8},
        "projects": ["Predictive Maintenance Pilot"], "certifications": [],
        "gaps": ["Robotics depth", "AI Ops"], "future_match": 67,
        "backup": "Developing Robotics backup alongside Travis and Cormac.",
        "plan": "Robotics verification on live work, AI Ops fundamentals.",
        "why": "Strong hands-on robotics exposure just below the verified-backup bar.",
        "future_gap": "Robotics 3.8 -> 4.9 is the main 2027 gap.",
    },
    {
        "id": "e-smal", "name": "Sana Malik", "role": "Maintenance Engineer", "department": "Operations", "team": "Plant Reliability",
        "confidence": 0.80, "freshness_days": 47, "growth_rate": 0.07,
        "interests": ["predictive maintenance"],
        "skills": {"SAP": 2.5, "FoodSafety": 2.8, "Robotics": 3.5, "ColdChain": 2.9, "AIOps": 2.6},
        "projects": ["Predictive Maintenance Pilot"], "certifications": [],
        "gaps": ["Robotics depth", "SAP"], "future_match": 61,
        "backup": "Developing - building Robotics depth.",
        "plan": "Robotics verification, SAP basics.",
        "why": "Solid maintenance fundamentals; needs more verified project evidence.",
        "future_gap": "Robotics 3.5 -> 4.9 for 2027 readiness.",
    },
    {
        "id": "e-dmur", "name": "Declan Murphy", "role": "Maintenance Engineer", "department": "Operations", "team": "Plant Reliability",
        "confidence": 0.78, "freshness_days": 61, "growth_rate": 0.06,
        "interests": ["reliability engineering"],
        "skills": {"SAP": 2.3, "FoodSafety": 2.6, "Robotics": 3.2, "ColdChain": 2.7, "AIOps": 2.4},
        "projects": [], "certifications": [],
        "gaps": ["Robotics depth", "AI Ops"], "future_match": 55,
        "backup": "Developing - not yet backup-eligible.",
        "plan": "Robotics fundamentals, AI Ops basics, live project exposure.",
        "why": "Newest to Maintenance; foundational skills present, evidence is aging.",
        "future_gap": "Robotics 3.2 -> 4.9 is the largest 2027 gap.",
    },
    {
        "id": "e-wcal", "name": "Wren Callahan", "role": "R&D Specialist", "department": "R&D", "team": "Product Innovation",
        "confidence": 0.84, "freshness_days": 31, "growth_rate": 0.12,
        "interests": ["sensory science", "product innovation"],
        "skills": {"SAP": 2.0, "FoodSafety": 3.8, "Robotics": 2.5, "ColdChain": 2.8, "AIOps": 2.9},
        "projects": ["Flavor Innovation Pilot"], "certifications": ["Food Science"],
        "gaps": ["Food Safety depth", "SAP"], "future_match": 66,
        "backup": "Developing R&D backup alongside Yuna and Talia.",
        "plan": "Food Safety verification on live work, SAP basics.",
        "why": "Strong, fresh R&D evidence just below the verified-backup bar.",
        "future_gap": "Food Safety 3.8 -> 4.7 closes most of the 2027 gap.",
    },
    {
        "id": "e-dsala", "name": "Diego Salazar", "role": "R&D Specialist", "department": "R&D", "team": "Product Innovation",
        "confidence": 0.81, "freshness_days": 42, "growth_rate": 0.10,
        "interests": ["product development"],
        "skills": {"SAP": 1.9, "FoodSafety": 3.6, "Robotics": 2.3, "ColdChain": 2.6, "AIOps": 2.7},
        "projects": [], "certifications": [],
        "gaps": ["Food Safety depth", "Robotics exposure"], "future_match": 62,
        "backup": "Developing - building R&D depth.",
        "plan": "Food Safety verification, robotics basics.",
        "why": "Consistent R&D fundamentals; needs a verified project to reach backup status.",
        "future_gap": "Food Safety 3.6 -> 4.7 for 2027 readiness.",
    },
    {
        "id": "e-mtan", "name": "Mei Lin Tan", "role": "R&D Specialist", "department": "R&D", "team": "Product Innovation",
        "confidence": 0.79, "freshness_days": 58, "growth_rate": 0.08,
        "interests": ["food science"],
        "skills": {"SAP": 1.8, "FoodSafety": 3.4, "Robotics": 2.1, "ColdChain": 2.5, "AIOps": 2.5},
        "projects": [], "certifications": [],
        "gaps": ["Food Safety depth", "evidence freshness"], "future_match": 57,
        "backup": "Developing - not yet backup-eligible.",
        "plan": "Food Safety verification, refresh evidence with live project work.",
        "why": "Early-stage R&D profile; evidence is aging and needs a live project.",
        "future_gap": "Food Safety 3.4 -> 4.7 is the largest 2027 gap.",
    },
    {
        "id": "e-kasan", "name": "Kwame Asante", "role": "Robotics Engineer", "department": "Engineering", "team": "Automation",
        "confidence": 0.87, "freshness_days": 19, "growth_rate": 0.18,
        "interests": ["industrial robotics", "AI-assisted operations"],
        "skills": {"SAP": 2.9, "FoodSafety": 2.4, "Robotics": 3.9, "ColdChain": 2.9, "AIOps": 3.6},
        "projects": ["Robotics Standards"], "certifications": ["Robotics Systems Integration"],
        "gaps": ["Robotics depth", "Food Safety exposure"], "future_match": 73,
        "backup": "Developing Robotics/AI Ops backup alongside Jonah and Valentina.",
        "plan": "Robotics verification on live work, Food Safety basics.",
        "why": "Fast-growing, fresh Robotics evidence just below the verified-backup bar.",
        "future_gap": "Robotics 3.9 -> 4.9 is the main 2027 gap.",
    },
    {
        "id": "e-idua", "name": "Ines Duarte", "role": "Robotics Engineer", "department": "Engineering", "team": "Automation",
        "confidence": 0.85, "freshness_days": 26, "growth_rate": 0.15,
        "interests": ["machine vision"],
        "skills": {"SAP": 2.7, "FoodSafety": 2.2, "Robotics": 3.6, "ColdChain": 2.7, "AIOps": 3.4},
        "projects": ["Vision Pilot"], "certifications": [],
        "gaps": ["Robotics depth", "SAP"], "future_match": 69,
        "backup": "Developing - building Robotics/AI Ops depth.",
        "plan": "Robotics verification, SAP basics.",
        "why": "Solid automation fundamentals with real vision-pilot exposure.",
        "future_gap": "Robotics 3.6 -> 4.9 for 2027 readiness.",
    },
    {
        "id": "e-oric", "name": "Otto Richter", "role": "Robotics Engineer", "department": "Engineering", "team": "Automation",
        "confidence": 0.82, "freshness_days": 37, "growth_rate": 0.12,
        "interests": ["automation strategy"],
        "skills": {"SAP": 2.5, "FoodSafety": 2.0, "Robotics": 3.3, "ColdChain": 2.5, "AIOps": 3.1},
        "projects": [], "certifications": [],
        "gaps": ["Robotics depth", "Food Safety exposure"], "future_match": 64,
        "backup": "Developing - not yet backup-eligible.",
        "plan": "Robotics fundamentals, Food Safety basics, live project exposure.",
        "why": "Early-stage automation profile; foundational skills present.",
        "future_gap": "Robotics 3.3 -> 4.9 is the largest 2027 gap.",
    },
    {
        "id": "e-bcos", "name": "Beatriz Costa", "role": "Mechanical Engineer", "department": "Engineering", "team": "Plant Engineering",
        "confidence": 0.84, "freshness_days": 24, "growth_rate": 0.10,
        "interests": ["equipment reliability"],
        "skills": {"SAP": 2.6, "FoodSafety": 2.5, "Robotics": 3.7, "ColdChain": 3.2, "AIOps": 2.7},
        "projects": ["Equipment Redesign"], "certifications": [],
        "gaps": ["Robotics depth", "SAP"], "future_match": 68,
        "backup": "Developing Mechanical/Robotics backup alongside Connor and Adelaide.",
        "plan": "Robotics verification on live work, SAP basics.",
        "why": "Fresh, well-rounded mechanical profile just below the verified-backup bar.",
        "future_gap": "Robotics 3.7 -> 4.9 is the main 2027 gap.",
    },
    {
        "id": "e-afitz", "name": "Aiden Fitzgerald", "role": "Mechanical Engineer", "department": "Engineering", "team": "Plant Engineering",
        "confidence": 0.81, "freshness_days": 36, "growth_rate": 0.08,
        "interests": ["mechanical design"],
        "skills": {"SAP": 2.4, "FoodSafety": 2.3, "Robotics": 3.4, "ColdChain": 3.0, "AIOps": 2.5},
        "projects": [], "certifications": [],
        "gaps": ["Robotics depth", "Food Safety"], "future_match": 62,
        "backup": "Developing - building mechanical/robotics depth.",
        "plan": "Robotics fundamentals, Food Safety basics.",
        "why": "Consistent mechanical fundamentals; needs a verified project for backup status.",
        "future_gap": "Robotics 3.4 -> 4.9 for 2027 readiness.",
    },
    {
        "id": "e-zahm", "name": "Zara Ahmed", "role": "Mechanical Engineer", "department": "Engineering", "team": "Plant Engineering",
        "confidence": 0.79, "freshness_days": 50, "growth_rate": 0.07,
        "interests": ["continuous improvement"],
        "skills": {"SAP": 2.2, "FoodSafety": 2.1, "Robotics": 3.1, "ColdChain": 2.8, "AIOps": 2.3},
        "projects": [], "certifications": [],
        "gaps": ["Robotics depth", "AI Ops"], "future_match": 56,
        "backup": "Developing - not yet backup-eligible.",
        "plan": "Robotics fundamentals, AI Ops basics, live project exposure.",
        "why": "Newest to Mechanical Engineering; foundational skills present, evidence still light.",
        "future_gap": "Robotics 3.1 -> 4.9 is the largest 2027 gap.",
    },
]

# Former employees never contribute to readiness/coverage/qualified-count/
# succession calculations - they are historical knowledge only, mirroring
# the frontend's formerEmployees[]. Deliberately NOT part of EMPLOYEES or
# STATE["employees"], and no engine.py function accepts this list.
FORMER_EMPLOYEES = [
    {
        "id": "raj",
        "name": "Arun Mehta",
        "former_role": "Senior Process Engineer",
        "department": "Engineering",
        "left_year": 2025,
        "tenure_years": 6,
        "skills": {"SAP": 4.4, "FoodSafety": 4.1, "Robotics": 4.0},
        "description": "Former Process Engineering role-holder. Historical work can support cross-training for process and SAP coverage.",
        "artifacts": ["Packaging Line SOP", "SAP changeover guide", "Robotics commissioning notes"],
    },
    {
        "id": "nina",
        "name": "Bridget Callahan",
        "former_role": "Process Engineer",
        "department": "Engineering",
        "left_year": 2024,
        "tenure_years": 4,
        "skills": {"FoodSafety": 4.2, "SAP": 3.9, "Robotics": 3.7},
        "description": "Former Process Engineer. Archived process-validation work can accelerate cross-training.",
        "artifacts": ["Yield-loss checklist", "Process validation template", "Packaging troubleshooting guide"],
    },
    {
        "id": "victor",
        "name": "Dmitri Volkov",
        "former_role": "Robotics Engineer",
        "department": "Engineering",
        "left_year": 2025,
        "tenure_years": 5,
        "skills": {"Robotics": 4.8, "AIOps": 3.9, "SAP": 3.2},
        "description": "Former Robotics Engineer. Commissioning and PLC documentation can accelerate robotics cross-training.",
        "artifacts": ["Robot commissioning checklist", "PLC backup archive", "Safety validation notes"],
    },
    {
        "id": "chloe",
        "name": "Freya Lindqvist",
        "former_role": "Robotics Engineer",
        "department": "Engineering",
        "left_year": 2024,
        "tenure_years": 4,
        "skills": {"Robotics": 4.4, "AIOps": 4.0, "ColdChain": 3.3},
        "description": "Former Robotics Engineer with reusable machine-vision and cobot knowledge.",
        "artifacts": ["Vision tuning guide", "Cobot risk assessment", "Robot maintenance handoff"],
    },
    {
        "id": "robert",
        "name": "Gordon Ashworth",
        "former_role": "Mechanical Engineer",
        "department": "Engineering",
        "left_year": 2025,
        "tenure_years": 8,
        "skills": {"Robotics": 4.0, "ColdChain": 3.8, "SAP": 3.0},
        "description": "Former Mechanical Engineer. Equipment drawings and failure history can support mechanical coverage.",
        "artifacts": ["Critical equipment drawings", "Mechanical failure library", "Engineering change notes"],
    },
    {
        "id": "elena",
        "name": "Rosalind Kessler",
        "former_role": "Maintenance Engineer",
        "department": "Operations",
        "left_year": 2024,
        "tenure_years": 6,
        "skills": {"Robotics": 4.1, "ColdChain": 3.5, "FoodSafety": 3.2},
        "description": "Former Maintenance Engineer. Reliability documentation can support cross-training and outage coverage.",
        "artifacts": ["PM standard work", "Failure-mode library", "Maintenance handoff checklist"],
    },
]

# Simple in-memory store for hackathon speed. Replace with Supabase/Postgres later.
STATE = {
    "employees": deepcopy(EMPLOYEES),
    "future_requirements": {k: v["future_target"] for k, v in SKILLS.items()},
    "business_impact": {
        k: {
            "daily_downtime_cost": v["daily_downtime_cost"],
            "default_recovery_days": v["default_recovery_days"],
        }
        for k, v in SKILLS.items()
    },
}


def reset_state():
    STATE["employees"] = deepcopy(EMPLOYEES)
    STATE["future_requirements"] = {k: v["future_target"] for k, v in SKILLS.items()}
    STATE["business_impact"] = {
        k: {
            "daily_downtime_cost": v["daily_downtime_cost"],
            "default_recovery_days": v["default_recovery_days"],
        }
        for k, v in SKILLS.items()
    }
